[package]
name = "class-06"
version = "0.1.0"
authors = ["HINA KHADIM <hinakhadim2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5.0"
surf="1"
futures = "0.3.4"