[package]
name = "class03"
version = "0.1.0"
authors = ["mrzaid <zaidahmed87861@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"